title: think.metavalent.com
description: Ask the Great and Powerful Awes! AI trained on all metavalent online content since 2004.

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
